import { DeliveryInfo } from "../types";

export const deliveryData: DeliveryInfo[] = [
  { code: 16, wilaya: "Alger", stopDeskEcommerce: 400, domicileEcommerce: 500 },
  { code: 2, wilaya: "Chlef", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 9, wilaya: "Blida", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 10, wilaya: "Bouira", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 15, wilaya: "Tizi Ouzou", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 19, wilaya: "Setif", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 25, wilaya: "Constantine", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 26, wilaya: "Medea", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 31, wilaya: "Oran", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 34, wilaya: "Bordj Bou Arreridj", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 35, wilaya: "Boumerdes", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 42, wilaya: "Tipaza", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 44, wilaya: "Ain Defla", stopDeskEcommerce: 400, domicileEcommerce: 700 },
  { code: 6, wilaya: "Bejaia", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 5, wilaya: "Batna", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 43, wilaya: "Mila", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 4, wilaya: "Oum El Bouaghi", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 13, wilaya: "Tlemcen", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 14, wilaya: "Tiaret", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 18, wilaya: "Jijel", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 21, wilaya: "Skikda", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 22, wilaya: "Sidi Bel Abbes", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 23, wilaya: "Annaba", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 27, wilaya: "Mostaganem", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 28, wilaya: "M'Sila", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 38, wilaya: "Tissemsilt", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 48, wilaya: "Relizane", stopDeskEcommerce: 450, domicileEcommerce: 750 },
  { code: 12, wilaya: "Tebessa", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 17, wilaya: "Djelfa", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 20, wilaya: "Saida", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 24, wilaya: "Guelma", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 29, wilaya: "Mascara", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 40, wilaya: "Khenchela", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 41, wilaya: "Souk Ahras", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 46, wilaya: "Ain Temouchent", stopDeskEcommerce: 500, domicileEcommerce: 800 },
  { code: 7, wilaya: "Biskra", stopDeskEcommerce: 550, domicileEcommerce: 850 },
  { code: 36, wilaya: "El Tarf", stopDeskEcommerce: 550, domicileEcommerce: 850 },
  { code: 51, wilaya: "Ouled Djellal", stopDeskEcommerce: null, domicileEcommerce: 900 },
  { code: 3, wilaya: "Laghouat", stopDeskEcommerce: 550, domicileEcommerce: 900 },
  { code: 57, wilaya: "El M'Ghair", stopDeskEcommerce: null, domicileEcommerce: 1000 },
  { code: 30, wilaya: "Ouargla", stopDeskEcommerce: 700, domicileEcommerce: 1000 },
  { code: 32, wilaya: "El Bayadh", stopDeskEcommerce: 700, domicileEcommerce: 1000 },
  { code: 39, wilaya: "El Oued", stopDeskEcommerce: 700, domicileEcommerce: 1000 },
  { code: 45, wilaya: "Naama", stopDeskEcommerce: 700, domicileEcommerce: 1000 },
  { code: 47, wilaya: "Ghardaia", stopDeskEcommerce: 700, domicileEcommerce: 1000 },
  { code: 55, wilaya: "Touggourt", stopDeskEcommerce: null, domicileEcommerce: 1100 },
  { code: 58, wilaya: "El Meniaa", stopDeskEcommerce: null, domicileEcommerce: 1100 },
  { code: 49, wilaya: "Timimoun", stopDeskEcommerce: null, domicileEcommerce: 1200 },
  { code: 52, wilaya: "Beni Abbes", stopDeskEcommerce: null, domicileEcommerce: 1200 },
  { code: 1, wilaya: "Adrar", stopDeskEcommerce: 900, domicileEcommerce: 1200 },
  { code: 8, wilaya: "Bechar", stopDeskEcommerce: 900, domicileEcommerce: 1200 },
  { code: 53, wilaya: "In Salah", stopDeskEcommerce: null, domicileEcommerce: 1400 },
  { code: 11, wilaya: "Tamanrasset", stopDeskEcommerce: 1100, domicileEcommerce: 1600 },
  { code: 54, wilaya: "In Guezzam", stopDeskEcommerce: null, domicileEcommerce: 1800 },
  { code: 33, wilaya: "Illizi", stopDeskEcommerce: null, domicileEcommerce: null },
  { code: 37, wilaya: "Tindouf", stopDeskEcommerce: null, domicileEcommerce: null },
  { code: 50, wilaya: "Bordj Badji Mokhtar", stopDeskEcommerce: null, domicileEcommerce: null },
  { code: 56, wilaya: "Djanet", stopDeskEcommerce: null, domicileEcommerce: null }
];
